spring:
  application:
    name: kkium
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jwt:
    secret: ${JWT_SECRET}
    access:
      token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  client-secret: ${KAKAO_CLIENT_SECRET}

notion:
  client-id: ${NOTION_CLIENT_ID}
  client-secret: ${NOTION_CLIENT_SECRET}
  redirect-uri: ${NOTION_REDIRECT_URI}
  frontend-redirect-uri: ${NOTION_FRONTEND_REDIRECT_URI}
  aes-secret-key: ${AES_SECRET_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: kkium
