spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

swagger:
  server:
    url: ${LOCAL_SWAGGER_URL}