spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    url: /v3/api-docs
  servers:
    - url: https://api.kkium.com
      description: Production Server