apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kkium-secret
  namespace: kkium
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: kkium-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_URL
    remoteRef:
      key: DB_URL
  - secretKey: DB_USER
    remoteRef:
      key: DB_USER
  - secretKey: DB_PASSWORD
    remoteRef:
      key: DB_PASSWORD
  - secretKey: JWT_SECRET
    remoteRef:
      key: JWT_SECRET
  - secretKey: JWT_ACCESS_TOKEN_EXPIRATION
    remoteRef:
      key: JWT_ACCESS_TOKEN_EXPIRATION
  - secretKey: KAKAO_REST_API_KEY
    remoteRef:
      key: KAKAO_REST_API_KEY
  - secretKey: KAKAO_REDIRECT_URI
    remoteRef:
      key: KAKAO_REDIRECT_URI
  - secretKey: KAKAO_CLIENT_SECRET
    remoteRef:
      key: KAKAO_CLIENT_SECRET
  - secretKey: GOOGLE_CLIENT_ID
    remoteRef:
      key: GOOGLE_CLIENT_ID
  - secretKey: GOOGLE_REDIRECT_URI
    remoteRef:
      key: GOOGLE_REDIRECT_URI
  - secretKey: GOOGLE_CLIENT_SECRET
    remoteRef:
      key: GOOGLE_CLIENT_SECRET
  - secretKey: GEMINI_API_KEY
    remoteRef:
      key: GEMINI_API_KEY
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: OPENAI_API_KEY
  - secretKey: NOTION_CLIENT_ID
    remoteRef:
      key: NOTION_CLIENT_ID
  - secretKey: NOTION_CLIENT_SECRET
    remoteRef:
      key: NOTION_CLIENT_SECRET
  - secretKey: NOTION_REDIRECT_URI
    remoteRef:
      key: NOTION_REDIRECT_URI
  - secretKey: NOTION_FRONTEND_REDIRECT_URI
    remoteRef:
      key: NOTION_FRONTEND_REDIRECT_URI
  - secretKey: AES_SECRET_KEY
    remoteRef:
      key: AES_SECRET_KEY
  - secretKey: REDIS_HOST
    remoteRef:
      key: REDIS_HOST
  - secretKey: GOOGLE_CLOUD_VISION_API_KEY
    remoteRef:
      key: GOOGLE_CLOUD_VISION_API_KEY
