apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: kkium
spec:
  provider:
    gcpsm:
      projectID: kkium-prod
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast3-a
          clusterName: kkium-cluster
          clusterProjectID: kkium-prod
          serviceAccountRef:
            name: kkium-external-secrets-ksa
            namespace: kkium
